#!/usr/bin/env python

# rkivas file backupper
# Copyright (C) 2016  Daniel Getz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import logging
from argparse import ArgumentParser

import rkivas.config
from rkivas import Archiver


parser = ArgumentParser()
rkivas.config.add_default_opts(parser)
opts = parser.parse_args()
cfg = rkivas.config.load_config(opts)
log = logging.getLogger('rkivas')

try:
    Archiver(cfg).archive_all()
except:
    log.fatal('Exiting due to error or signal', exc_info=True)
finally:
    logging.shutdown()
